version: '3.8'
services:
  webserver:
    image: webserver
    build:
      context: .
      dockerfile: WebServer/Dockerfile
    ports:
      - "5000:8080"  # Host:5000 → Container:8080

  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "5001:8080"  # Host:5001 → Container:8080
