version: '3.8'
services:
  webserver:
    build:
      context: .
      dockerfile: WebServerRazor/Dockerfile
    ports:
      - "5000:8080"  # Host 5000 -> Container 8080
    # you can name the container if you like:
    container_name: webserverSpike

  webapi:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "5001:8080"  # Host 5001 -> Container 8080
    container_name: webapiSpike
