# TerraGroupLabs/docker-compose.yml
version: '3.8'

services:
  spacetimedb_server:
    image: clockworklabs/spacetime:latest
    container_name: spacetimedb_chat_server
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    volumes:
      # Mount the AppBundle directory (containing server.wasm)
      - ./code/TerraGroupLabs/server/bin/Release/net8.0/wasi-wasm/AppBundle:/module:ro
      # This volume will be /data inside the container.
      # Both publish (implicitly) and start (explicitly) need to use this.
      - spacetimedb_chat_data:/data
    entrypoint: /bin/sh
    command:
      - -c
      - |
        set -e # Exit on any error

        echo 'Attempting to publish module, hoping it uses a local data context aligned with /data...'
        # We use -y to avoid prompts.
        # We use -b to point to the pre-compiled WASM.
        # We provide "tg-labs-chat" as the name.
        # We are NOT providing -s (server), hoping this defaults to a local operation
        # that stores module metadata in a way that `start --data-dir /data` can find it.
        # The publish command itself needs to know to use `/data` as its working space.
        # If it defaults to something like /home/spacetime/.spacetime, we have a mismatch.
        #
        # One trick: if the CLI's default data dir can be influenced by `working_dir`
        # or if certain files in `working_dir` influence it.
        # Let's set working_dir to /data, hoping publish picks it up as context.
        cd /data # Change working directory to /data before publishing

        echo "Current directory: $(pwd)"
        echo "Publishing module 'tg-labs-chat' from /module/server.wasm"
        spacetime publish -y -b /module/server.wasm tg-labs-chat

        echo 'Publish command completed. Starting server...'
        # Start command explicitly uses /data, which should now contain the published module info.
        # Removed --dev as it's not supported by this `start` command.
        exec spacetime start --listen-addr 0.0.0.0:3000 --data-dir /data
volumes:
  spacetimedb_chat_data: