# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  webapi:
    build:
      context: "/home/twosix/Documents/GitHub/TerraGroupLabs/code/TerraGroupLabs"
      dockerfile: "WebAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WebAPI.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webapi:dev"
    ports: []
    volumes:
    - "/home/twosix/.nuget/packages:/home/app/.nuget/packages"
    - "/home/twosix/Documents/GitHub/TerraGroupLabs/code/TerraGroupLabs/WebAPI:/app:rw"
    - "/home/twosix/Documents/GitHub/TerraGroupLabs/code/TerraGroupLabs:/src:rw"
    working_dir: "/app"
  webserver:
    build:
      context: "/home/twosix/Documents/GitHub/TerraGroupLabs/code/TerraGroupLabs"
      dockerfile: "WebServerRazor/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WebServerRazor.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/WebServerRazor.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webserverrazor:dev"
    ports: []
    volumes:
    - "/home/twosix/.nuget/packages:/home/app/.nuget/packages"
    - "/home/twosix/Documents/GitHub/TerraGroupLabs/code/TerraGroupLabs/WebServerRazor:/app:rw"
    - "/home/twosix/Documents/GitHub/TerraGroupLabs/code/TerraGroupLabs:/src:rw"
    working_dir: "/app"
